# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Velar' do

  # https://github.com/prolificinteractive/Moulinette
  pod 'Moulinette', '0.1.4', :configurations => ['Debug']

  target 'VelarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VelarUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
